export interface ListItem {
    id: string;
    listName: string;
    startDate: string;
    endDate: string;
    influencer: string;
    influencerImage: string;
    dealName: string;
    description: string;
    status: string;
    payment: string;
    nightStar: string;
    location: string;
}

export const lists: ListItem[] = [
    {
        id: "1",
        listName: "GreenStay Villa",
        startDate: "2025-11-27",
        endDate: "2025-12-27",
        influencer: "John Doe",
        influencerImage: "https://picsum.photos/400?random=1",
        dealName: "GreenStay Villa",
        description: "A modern eco-friendly apartment offering a peaceful coastal stay.",
        status: "active",
        payment: "$200",
        nightStar: "3",
        location: "Miami Beach, Florida",
    },
    {
        id: "2",
        listName: "Ocean Breeze Retreat",
        startDate: "2025-11-15",
        endDate: "2025-12-05",
        influencer: "Jane Smith",
        influencerImage: "https://picsum.photos/400?random=2",
        dealName: "Ocean Breeze Retreat",
        description: "Relax by the beach with stunning ocean views and modern amenities.",
        status: "requesting",
        payment: "$180",
        nightStar: "4",
        location: "San Diego, California",
    },
    {
        id: "3",
        listName: "Mountain Escape Lodge",
        startDate: "2025-12-01",
        endDate: "2025-12-20",
        influencer: "David Lee",
        influencerImage: "https://picsum.photos/400?random=3",
        dealName: "Mountain Escape Lodge",
        description: "A serene getaway in the mountains, perfect for nature lovers.",
        status: "completed",
        payment: "$250",
        nightStar: "5",
        location: "Aspen, Colorado",
    },
    {
        id: "4",
        listName: "Skyline Penthouse",
        startDate: "2025-12-10",
        endDate: "2025-12-30",
        influencer: "Emily Turner",
        influencerImage: "https://picsum.photos/400?random=4",
        dealName: "Skyline Penthouse",
        description: "Luxurious penthouse with panoramic city views and private amenities.",
        status: "pending",
        payment: "$500",
        nightStar: "5",
        location: "New York, New York",
    },
    {
        id: "5",
        listName: "Lakeside Villa",
        startDate: "2025-12-05",
        endDate: "2025-12-25",
        influencer: "Sophie Chen",
        influencerImage: "https://picsum.photos/400?random=5",
        dealName: "Lakeside Villa",
        description: "A peaceful retreat by the lake, ideal for a relaxing vacation.",
        status: "active",
        payment: "$220",
        nightStar: "4",
        location: "Lake Tahoe, California",
    },
    {
        id: "6",
        listName: "Desert Oasis",
        startDate: "2025-12-15",
        endDate: "2025-12-30",
        influencer: "Oliver Green",
        influencerImage: "https://picsum.photos/400?random=6",
        dealName: "Desert Oasis",
        description: "A luxurious stay in the desert with a private pool and spa.",
        status: "requesting",
        payment: "$320",
        nightStar: "5",
        location: "Sedona, Arizona",
    },
    {
        id: "7",
        listName: "Seaside Cottage",
        startDate: "2025-11-10",
        endDate: "2025-11-20",
        influencer: "Grace Miller",
        influencerImage: "https://picsum.photos/400?random=7",
        dealName: "Seaside Cottage",
        description: "Cozy cottage steps from the beach, perfect for a weekend getaway.",
        status: "completed",
        payment: "$150",
        nightStar: "3",
        location: "Santa Cruz, California",
    },
    {
        id: "8",
        listName: "Villa Solaria",
        startDate: "2025-11-01",
        endDate: "2025-11-30",
        influencer: "Liam Williams",
        influencerImage: "https://picsum.photos/400?random=8",
        dealName: "Villa Solaria",
        description: "A luxurious villa with a stunning infinity pool and panoramic views.",
        status: "active",
        payment: "$450",
        nightStar: "5",
        location: "Napa Valley, California",
    },
    {
        id: "9",
        listName: "Urban Loft",
        startDate: "2025-11-20",
        endDate: "2025-12-10",
        influencer: "Sophia Harris",
        influencerImage: "https://picsum.photos/400?random=9",
        dealName: "Urban Loft",
        description: "Stylish loft in the heart of the city, close to restaurants and nightlife.",
        status: "pending",
        payment: "$300",
        nightStar: "4",
        location: "Chicago, Illinois",
    },
    {
        id: "10",
        listName: "Forest Retreat",
        startDate: "2025-11-25",
        endDate: "2025-12-05",
        influencer: "Mason Clark",
        influencerImage: "https://picsum.photos/400?random=10",
        dealName: "Forest Retreat",
        description: "A rustic retreat in the forest, offering peace and tranquility.",
        status: "requesting",
        payment: "$180",
        nightStar: "4",
        location: "Portland, Oregon",
    },
    {
        id: "11",
        listName: "Tropical Escape",
        startDate: "2025-11-01",
        endDate: "2025-11-25",
        influencer: "Amelia Thompson",
        influencerImage: "https://picsum.photos/400?random=11",
        dealName: "Tropical Escape",
        description: "A beachside bungalow with lush tropical gardens and a private beach.",
        status: "pending",
        payment: "$350",
        nightStar: "5",
        location: "Kauai, Hawaii",
    },
    {
        id: "12",
        listName: "Sunset Beach House",
        startDate: "2025-12-01",
        endDate: "2025-12-15",
        influencer: "Ethan Scott",
        influencerImage: "https://picsum.photos/400?random=12",
        dealName: "Sunset Beach House",
        description: "A spacious beach house with breathtaking sunset views every evening.",
        status: "active",
        payment: "$275",
        nightStar: "4",
        location: "Santa Barbara, California",
    },
    {
        id: "13",
        listName: "City View Penthouse",
        startDate: "2025-12-05",
        endDate: "2025-12-25",
        influencer: "Isabella Davis",
        influencerImage: "https://picsum.photos/400?random=13",
        dealName: "City View Penthouse",
        description: "Enjoy the city skyline from this chic penthouse apartment.",
        status: "pending",
        payment: "$400",
        nightStar: "5",
        location: "Los Angeles, California",
    },
    {
        id: "14",
        listName: "Riverside Retreat",
        startDate: "2025-11-10",
        endDate: "2025-11-30",
        influencer: "Michael Jordan",
        influencerImage: "https://picsum.photos/400?random=14",
        dealName: "Riverside Retreat",
        description: "A peaceful riverside retreat with cozy amenities and outdoor seating.",
        status: "pending",
        payment: "$200",
        nightStar: "3",
        location: "Austin, Texas",
    },
    {
        id: "15",
        listName: "Alpine Resort",
        startDate: "2025-12-05",
        endDate: "2025-12-20",
        influencer: "Anna Carter",
        influencerImage: "https://picsum.photos/400?random=15",
        dealName: "Alpine Resort",
        description: "A ski resort offering luxury accommodations and breathtaking mountain views.",
        status: "requesting",
        payment: "$500",
        nightStar: "5",
        location: "Vail, Colorado",
    },
    {
        id: "16",
        listName: "Beachside Mansion",
        startDate: "2025-12-01",
        endDate: "2025-12-15",
        influencer: "Lucas Harris",
        influencerImage: "https://picsum.photos/400?random=16",
        dealName: "Beachside Mansion",
        description: "An exclusive mansion with private beach access and luxurious amenities.",
        status: "active",
        payment: "$800",
        nightStar: "5",
        location: "Malibu, California",
    },
    {
        id: "17",
        listName: "Historic Townhouse",
        startDate: "2025-11-18",
        endDate: "2025-12-08",
        influencer: "Ava Miller",
        influencerImage: "https://picsum.photos/400?random=17",
        dealName: "Historic Townhouse",
        description: "A charming historic townhouse with a cozy fireplace and antique furnishings.",
        status: "active",
        payment: "$220",
        nightStar: "4",
        location: "San Francisco, California",
    },
    {
        id: "18",
        listName: "Mountain Cabin",
        startDate: "2025-12-05",
        endDate: "2025-12-25",
        influencer: "Oliver Green",
        influencerImage: "https://picsum.photos/400?random=18",
        dealName: "Mountain Cabin",
        description: "A cozy cabin nestled in the mountains, offering a peaceful retreat.",
        status: "pending",
        payment: "$150",
        nightStar: "3",
        location: "Boulder, Colorado",
    },
    {
        id: "19",
        listName: "Beachfront Bungalow",
        startDate: "2025-11-20",
        endDate: "2025-12-10",
        influencer: "Grace Miller",
        influencerImage: "https://picsum.photos/400?random=19",
        dealName: "Beachfront Bungalow",
        description: "A cozy bungalow with a private beach and a deck for enjoying the sunset.",
        status: "requesting",
        payment: "$280",
        nightStar: "4",
        location: "Hawaii, Hawaii",
    },
    {
        id: "20",
        listName: "Luxury Penthouse",
        startDate: "2025-12-01",
        endDate: "2025-12-20",
        influencer: "Ethan Scott",
        influencerImage: "https://picsum.photos/400?random=20",
        dealName: "Luxury Penthouse",
        description: "A luxurious penthouse with a private terrace and stunning city views.",
        status: "active",
        payment: "$600",
        nightStar: "5",
        location: "New York, New York",
    },
    {
        id: "21",
        listName: "Rustic Cabin",
        startDate: "2025-11-15",
        endDate: "2025-12-05",
        influencer: "Sophia Harris",
        influencerImage: "https://picsum.photos/400?random=21",
        dealName: "Rustic Cabin",
        description: "A cozy cabin with a wood-burning fireplace and a private hot tub.",
        status: "pending",
        payment: "$220",
        nightStar: "4",
        location: "Aspen, Colorado",
    },
    {
        id: "22",
        listName: "Beachside Bungalow",
        startDate: "2025-12-05",
        endDate: "2025-12-25",
        influencer: "Mason Clark",
        influencerImage: "https://picsum.photos/400?random=22",
        dealName: "Beachside Bungalow",
        description: "A cozy bungalow with a private beach and a deck for enjoying the sunset.",
        status: "active",
        payment: "$280",
        nightStar: "4",
        location: "Hawaii, Hawaii",
    },
    {
        id: "23",
        listName: "Luxury Penthouse",
        startDate: "2025-12-01",
        endDate: "2025-12-20",
        influencer: "Isabella Davis",
        influencerImage: "https://picsum.photos/400?random=23",
        dealName: "Luxury Penthouse",
        description: "A luxurious penthouse with a private terrace and stunning city views.",
        status: "requesting",
        payment: "$600",
        nightStar: "5",
        location: "New York, New York",
    },
    {
        id: "24",
        listName: "Rustic Cabin",
        startDate: "2025-11-15",
        endDate: "2025-12-05",
        influencer: "Michael Jordan",
        influencerImage: "https://picsum.photos/400?random=24",
        dealName: "Rustic Cabin",
        description: "A cozy cabin with a wood-burning fireplace and a private hot tub.",
        status: "pending",
        payment: "$220",
        nightStar: "4",
        location: "Aspen, Colorado",
    },
    {
        id: "25",
        listName: "Beachside Bungalow",
        startDate: "2025-12-05",
        endDate: "2025-12-25",
        influencer: "Anna Carter",
        influencerImage: "https://picsum.photos/400?random=25",
        dealName: "Beachside Bungalow",
        description: "A cozy bungalow with a private beach and a deck for enjoying the sunset.",
        status: "active",
        payment: "$280",
        nightStar: "4",
        location: "Hawaii, Hawaii",
    },
    {
        id: "26",
        listName: "Luxury Penthouse",
        startDate: "2025-12-01",
        endDate: "2025-12-20",
        influencer: "Lucas Harris",
        influencerImage: "https://picsum.photos/400?random=26",
        dealName: "Luxury Penthouse",
        description: "A luxurious penthouse with a private terrace and stunning city views.",
        status: "requesting",
        payment: "$600",
        nightStar: "5",
        location: "New York, New York",
    },
    {
        id: "27",
        listName: "Rustic Cabin",
        startDate: "2025-11-15",
        endDate: "2025-12-05",
        influencer: "Ava Miller",
        influencerImage: "https://picsum.photos/400?random=27",
        dealName: "Rustic Cabin",
        description: "A cozy cabin with a wood-burning fireplace and a private hot tub.",
        status: "pending",
        payment: "$220",
        nightStar: "4",
        location: "Aspen, Colorado",
    }
]

