export interface Deal {
    id: string;
    name: string;
    influencer: string;
    status: "active" | "pending" | "completed";
    amount: string;
    startDate: string;
    endDate: string;
    category: string;
}

export const deals: Deal[] = [
    {
        id: "1",
        name: "Summer Collection Campaign",
        influencer: "John Doe",
        status: "active",
        startDate: "01/01/2026",
        endDate: "01/01/2026",
        amount: "$2,500.00",
        category: "Fashion",
    },
    {
        id: "2",
        name: "Tech Gadgets Launch",
        influencer: "Sarah Johnson",
        status: "pending",
        amount: "$1,800.00",
        startDate: "02/15/2026",
        endDate: "03/15/2026",
        category: "Technology",
    },
    {
        id: "3",
        name: "Fitness App Promotion",
        influencer: "Mike Chen",
        status: "active",
        amount: "$3,200.00",
        startDate: "01/10/2026",
        endDate: "02/10/2026",
        category: "Health & Fitness",
    },
    {
        id: "4",
        name: "Food Festival Sponsorship",
        influencer: "Emma Wilson",
        status: "completed",
        amount: "$1,200.00",
        startDate: "12/01/2025",
        endDate: "12/15/2025",
        category: "Food & Beverage",
    },
    {
        id: "5",
        name: "Travel Vlog Series",
        influencer: "Alex Rivera",
        status: "completed",
        amount: "$4,500.00",
        startDate: "11/01/2025",
        endDate: "11/30/2025",
        category: "Travel",
    },
    {
        id: "6",
        name: "Winter Jacket Promo",
        influencer: "Liam Brown",
        status: "active",
        amount: "$2,900.00",
        startDate: "12/20/2025",
        endDate: "01/20/2026",
        category: "Fashion",
    },
    {
        id: "7",
        name: "Smart Home Devices Awareness",
        influencer: "Olivia Green",
        status: "pending",
        amount: "$3,600.00",
        startDate: "03/01/2026",
        endDate: "04/01/2026",
        category: "Technology",
    },
    {
        id: "8",
        name: "Yoga Mat Branding",
        influencer: "Sophia Patel",
        status: "completed",
        amount: "$1,450.00",
        startDate: "10/10/2025",
        endDate: "10/25/2025",
        category: "Health & Fitness",
    },
    {
        id: "9",
        name: "Organic Snacks Promotion",
        influencer: "Daniel Kim",
        status: "active",
        amount: "$2,200.00",
        startDate: "01/05/2026",
        endDate: "02/05/2026",
        category: "Food & Beverage",
    },
    {
        id: "10",
        name: "Luxury Resort Giveaway",
        influencer: "Mia Anderson",
        status: "pending",
        amount: "$5,000.00",
        startDate: "04/01/2026",
        endDate: "04/30/2026",
        category: "Travel",
    },
    {
        id: "11",
        name: "Skincare Routine Campaign",
        influencer: "Ava Martinez",
        status: "active",
        amount: "$2,750.00",
        startDate: "02/01/2026",
        endDate: "03/01/2026",
        category: "Beauty",
    },
    {
        id: "12",
        name: "Mobile App Growth Push",
        influencer: "Noah Williams",
        status: "completed",
        amount: "$3,900.00",
        startDate: "09/01/2025",
        endDate: "09/30/2025",
        category: "Technology",
    },
    {
        id: "13",
        name: "Protein Powder Launch",
        influencer: "Chloe Singh",
        status: "active",
        amount: "$1,900.00",
        startDate: "01/15/2026",
        endDate: "02/15/2026",
        category: "Health & Fitness",
    },
    {
        id: "14",
        name: "Street Food Tour Coverage",
        influencer: "Ethan Carter",
        status: "completed",
        amount: "$1,150.00",
        startDate: "08/10/2025",
        endDate: "08/25/2025",
        category: "Food & Beverage",
    },
    {
        id: "15",
        name: "Adventure Travel Experience",
        influencer: "Zara Lopez",
        status: "pending",
        amount: "$4,700.00",
        startDate: "05/05/2026",
        endDate: "06/05/2026",
        category: "Travel",
    },
    {
        id: "16",
        name: "Streetwear Brand Drop",
        influencer: "Logan Hughes",
        status: "active",
        amount: "$3,300.00",
        startDate: "03/01/2026",
        endDate: "03/25/2026",
        category: "Fashion",
    },
    {
        id: "17",
        name: "VR Headset Review Series",
        influencer: "Harper Scott",
        status: "pending",
        amount: "$4,200.00",
        startDate: "04/10/2026",
        endDate: "05/10/2026",
        category: "Technology",
    },
    {
        id: "18",
        name: "Healthy Eating Challenge",
        influencer: "Ella Brooks",
        status: "completed",
        amount: "$1,800.00",
        startDate: "07/01/2025",
        endDate: "07/20/2025",
        category: "Health & Fitness",
    },
    {
        id: "19",
        name: "Gourmet Desserts Week",
        influencer: "James Turner",
        status: "active",
        amount: "$1,650.00",
        startDate: "02/10/2026",
        endDate: "03/10/2026",
        category: "Food & Beverage",
    },
    {
        id: "20",
        name: "Island Travel Guide",
        influencer: "Nina Flores",
        status: "completed",
        amount: "$4,300.00",
        startDate: "09/01/2025",
        endDate: "09/30/2025",
        category: "Travel",
    },
    {
        id: "21",
        name: "Makeup Essentials Launch",
        influencer: "Bella Rossi",
        status: "pending",
        amount: "$2,350.00",
        startDate: "03/05/2026",
        endDate: "04/05/2026",
        category: "Beauty",
    },
    {
        id: "22",
        name: "Crypto Wallet Promotion",
        influencer: "Max Harris",
        status: "active",
        amount: "$5,500.00",
        startDate: "01/20/2026",
        endDate: "02/20/2026",
        category: "Technology",
    },
    {
        id: "23",
        name: "Running Shoes Endurance Test",
        influencer: "Zoe Mitchell",
        status: "completed",
        amount: "$2,150.00",
        startDate: "10/05/2025",
        endDate: "10/30/2025",
        category: "Health & Fitness",
    },
    {
        id: "24",
        name: "Café Tasting Tour",
        influencer: "Oliver Bennett",
        status: "active",
        amount: "$1,300.00",
        startDate: "02/01/2026",
        endDate: "02/20/2026",
        category: "Food & Beverage",
    },
    {
        id: "25",
        name: "Historic Cities Travel Series",
        influencer: "Ruby Adams",
        status: "pending",
        amount: "$4,800.00",
        startDate: "06/01/2026",
        endDate: "07/01/2026",
        category: "Travel",
    },
    {
        id: "26",
        name: "Designer Handbags Launch",
        influencer: "Grace Morgan",
        status: "active",
        amount: "$3,750.00",
        startDate: "01/10/2026",
        endDate: "02/10/2026",
        category: "Fashion",
    },
    {
        id: "27",
        name: "AI Productivity App Promo",
        influencer: "Henry Reed",
        status: "completed",
        amount: "$2,950.00",
        startDate: "11/01/2025",
        endDate: "11/20/2025",
        category: "Technology",
    },
    {
        id: "28",
        name: "Gym Equipment Demo Series",
        influencer: "Sofia Perez",
        status: "pending",
        amount: "$3,400.00",
        startDate: "04/15/2026",
        endDate: "05/15/2026",
        category: "Health & Fitness",
    },
    {
        id: "29",
        name: "Street Food Carnival",
        influencer: "Jason Ward",
        status: "active",
        amount: "$1,750.00",
        startDate: "03/01/2026",
        endDate: "03/15/2026",
        category: "Food & Beverage",
    },
    {
        id: "30",
        name: "Budget Travel Hacks",
        influencer: "Emily Parker",
        status: "completed",
        amount: "$2,600.00",
        startDate: "08/01/2025",
        endDate: "08/25/2025",
        category: "Travel",
    },
    {
        id: "31",
        name: "Sneaker Branding Collab",
        influencer: "Leo Foster",
        status: "active",
        amount: "$3,900.00",
        startDate: "02/20/2026",
        endDate: "03/20/2026",
        category: "Fashion",
    },
    {
        id: "32",
        name: "Laptop Review Challenge",
        influencer: "Hannah Davis",
        status: "pending",
        amount: "$5,200.00",
        startDate: "05/10/2026",
        endDate: "06/10/2026",
        category: "Technology",
    },
    {
        id: "33",
        name: "Home Workout Plan Promo",
        influencer: "Aiden Moore",
        status: "completed",
        amount: "$1,980.00",
        startDate: "09/15/2025",
        endDate: "10/05/2025",
        category: "Health & Fitness",
    },
    {
        id: "34",
        name: "Culinary Street Tour Promo",
        influencer: "Isla Reed",
        status: "active",
        amount: "$1,550.00",
        startDate: "02/25/2026",
        endDate: "03/10/2026",
        category: "Food & Beverage",
    },
    {
        id: "35",
        name: "Tropical Island Vlog Series",
        influencer: "Mason Price",
        status: "pending",
        amount: "$4,950.00",
        startDate: "07/01/2026",
        endDate: "07/30/2026",
        category: "Travel",
    },
];
