export interface ListItem {
    id: string;
    name: string;
    location: string;
    date: string;
    propertyType: string;
    image: string;
    description: string;
    status: string;
}

export const lists: ListItem[] = [
    {
        id: "1",
        name: "GreenStay Villa",
        date: "2025-11-27",
        propertyType: "Apartment",
        image: "https://picsum.photos/400?random=1",
        description: "A modern eco-friendly apartment offering a peaceful coastal stay.",
        status: "Verified",
        location: "Miami Beach, Florida",
    },
    {
        id: "2",
        name: "Sunset Crest Resort",
        date: "2025-10-02",
        propertyType: "Resort",
        image: "https://picsum.photos/400?random=2",
        description: "Luxury beachfront resort with sunset views and premium amenities.",
        status: "Pending",
        location: "Los Angeles, California",
    },
    {
        id: "3",
        name: "UrbanNest Suites",
        date: "2025-09-18",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=3",
        description: "Business-friendly hotel located in the heart of the city.",
        status: "Verified",
        location: "Chicago, Illinois",
    },
    {
        id: "4",
        name: "PalmLeaf Residency",
        date: "2025-08-12",
        propertyType: "Villa",
        image: "https://picsum.photos/400?random=4",
        description: "Tropical villa surrounded by palm trees and natural serenity.",
        status: "Verified",
        location: "Orlando, Florida",
    },
    {
        id: "5",
        name: "LuxeBay Apartments",
        date: "2025-07-21",
        propertyType: "Apartment",
        image: "https://picsum.photos/400?random=5",
        description: "Premium waterfront apartments offering ocean views.",
        status: "Verified",
        location: "San Diego, California",
    },
    {
        id: "6",
        name: "Evergreen Hills Lodge",
        date: "2025-06-30",
        propertyType: "Lodge",
        image: "https://picsum.photos/400?random=6",
        description: "Nature-inspired lodge perfect for mountain retreats.",
        status: "Pending",
        location: "Denver, Colorado",
    },
    {
        id: "7",
        name: "BlueWater Harmony Stay",
        date: "2025-05-14",
        propertyType: "Resort",
        image: "https://picsum.photos/400?random=7",
        description: "Resort featuring ocean-side pools and a relaxing atmosphere.",
        status: "Verified",
        location: "Honolulu, Hawaii",
    },
    {
        id: "8",
        name: "PeakView Cabin",
        date: "2025-04-29",
        propertyType: "Cabin",
        image: "https://picsum.photos/400?random=8",
        description: "Rustic wooden cabin with stunning mountain views.",
        status: "Verified",
        location: "Aspen, Colorado",
    },
    {
        id: "9",
        name: "SilverStone Inn",
        date: "2025-04-03",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=9",
        description: "Comfortable city inn offering business-class services.",
        status: "Pending",
        location: "Boston, Massachusetts",
    },
    {
        id: "10",
        name: "CrystalHaven Villa",
        date: "2025-03-22",
        propertyType: "Villa",
        image: "https://picsum.photos/400?random=10",
        description: "A luxury villa with private pool and quiet surroundings.",
        status: "Verified",
        location: "Scottsdale, Arizona",
    },
    {
        id: "11",
        name: "OceanBreeze Retreat",
        date: "2025-02-16",
        propertyType: "Resort",
        image: "https://picsum.photos/400?random=11",
        description: "Seaside retreat known for its calm breeze and relaxing vibes.",
        status: "Verified",
        location: "Tampa, Florida",
    },
    {
        id: "12",
        name: "MountainSoul Cabin",
        date: "2025-02-01",
        propertyType: "Cabin",
        image: "https://picsum.photos/400?random=12",
        description: "Cozy cabin surrounded by pine forests and hiking trails.",
        status: "Verified",
        location: "Jackson Hole, Wyoming",
    },
    {
        id: "13",
        name: "RoyalOak Estate",
        date: "2025-01-18",
        propertyType: "Villa",
        image: "https://picsum.photos/400?random=13",
        description: "A grand villa estate offering premium luxury and comfort.",
        status: "Verified",
        location: "Austin, Texas",
    },
    {
        id: "14",
        name: "HarborFront Suites",
        date: "2025-01-03",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=14",
        description: "Modern waterfront hotel with marina access.",
        status: "Pending",
        location: "Seattle, Washington",
    },
    {
        id: "15",
        name: "CanyonEdge Lodge",
        date: "2024-12-25",
        propertyType: "Lodge",
        image: "https://picsum.photos/400?random=15",
        description: "Scenic lodge located near the canyon cliffs.",
        status: "Verified",
        location: "Grand Canyon, Arizona",
    },
    {
        id: "16",
        name: "Skyline Deluxe Apartments",
        date: "2024-12-10",
        propertyType: "Apartment",
        image: "https://picsum.photos/400?random=16",
        description: "High-rise apartments with panoramic city views.",
        status: "Verified",
        location: "New York City, New York",
    },
    {
        id: "17",
        name: "GoldenDunes Resort",
        date: "2024-11-30",
        propertyType: "Resort",
        image: "https://picsum.photos/400?random=17",
        description: "Resort famous for desert dunes adventures and luxury stays.",
        status: "Verified",
        location: "Palm Springs, California",
    },
    {
        id: "18",
        name: "ForestWhisper Cabin",
        date: "2024-11-12",
        propertyType: "Cabin",
        image: "https://picsum.photos/400?random=18",
        description: "Quiet forest cabin perfect for peaceful getaways.",
        status: "Verified",
        location: "Boise, Idaho",
    },
    {
        id: "19",
        name: "BlueLagoon Residency",
        date: "2024-10-28",
        propertyType: "Apartment",
        image: "https://picsum.photos/400?random=19",
        description: "Luxury apartments beside the famous blue lagoon waters.",
        status: "Pending",
        location: "Key West, Florida",
    },
    {
        id: "20",
        name: "CedarPeak Inn",
        date: "2024-10-10",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=20",
        description: "Boutique inn featuring handcrafted cedar decor.",
        status: "Verified",
        location: "Portland, Oregon",
    },
    {
        id: "21",
        name: "OceanPearl Villa",
        date: "2024-09-22",
        propertyType: "Villa",
        image: "https://picsum.photos/400?random=21",
        description: "Private villa with crystal-clear waters and exclusive access.",
        status: "Verified",
        location: "Malibu, California",
    },
    {
        id: "22",
        name: "MetroHub Suites",
        date: "2024-09-05",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=22",
        description: "Stylish city hotel located near major metro stations.",
        status: "Pending",
        location: "Houston, Texas",
    },
    {
        id: "23",
        name: "TimberLeaf Cabin",
        date: "2024-08-14",
        propertyType: "Cabin",
        image: "https://picsum.photos/400?random=23",
        description: "Handcrafted wooden cabin with a warm cozy feel.",
        status: "Verified",
        location: "Salt Lake City, Utah",
    },
    {
        id: "24",
        name: "HorizonEdge Resort",
        date: "2024-08-01",
        propertyType: "Resort",
        image: "https://picsum.photos/400?random=24",
        description: "Cliff-side resort offering breathtaking sunrise views.",
        status: "Verified",
        location: "Big Sur, California",
    },
    {
        id: "25",
        name: "CityGate Residency",
        date: "2024-07-11",
        propertyType: "Apartment",
        image: "https://picsum.photos/400?random=25",
        description: "Urban residential spaces with modern architecture.",
        status: "Verified",
        location: "Atlanta, Georgia",
    },
    {
        id: "26",
        name: "Riverside Heritage Inn",
        date: "2024-06-29",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=26",
        description: "Vintage inn located beside the calming riverside.",
        status: "Pending",
        location: "Richmond, Virginia",
    },
    {
        id: "27",
        name: "CoralView Villa",
        date: "2024-06-12",
        propertyType: "Villa",
        image: "https://picsum.photos/400?random=27",
        description: "Elegant villa with underwater coral exploration activities.",
        status: "Verified",
        location: "Key Largo, Florida",
    },
    {
        id: "28",
        name: "SummitShade Lodge",
        date: "2024-05-19",
        propertyType: "Lodge",
        image: "https://picsum.photos/400?random=28",
        description: "Lodge located in shaded mountain areas with cool atmosphere.",
        status: "Verified",
        location: "Lake Tahoe, California",
    },
    {
        id: "29",
        name: "HarborLine Suites",
        date: "2024-05-01",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=29",
        description: "Comfortable suites overlooking the busy harbor.",
        status: "Verified",
        location: "Baltimore, Maryland",
    },
    {
        id: "30",
        name: "GoldenLeaf Apartments",
        date: "2024-04-17",
        propertyType: "Apartment",
        image: "https://picsum.photos/400?random=30",
        description: "Premium apartments surrounded by golden autumn trees.",
        status: "Verified",
        location: "Minneapolis, Minnesota",
    },
    {
        id: "31",
        name: "ParadiseBay Resort",
        date: "2024-03-23",
        propertyType: "Resort",
        image: "https://picsum.photos/400?random=31",
        description: "High-end resort known for its crystal-blue private beaches.",
        status: "Pending",
        location: "Honolulu, Hawaii",
    },
    {
        id: "32",
        name: "TranquilNest Cabin",
        date: "2024-03-04",
        propertyType: "Cabin",
        image: "https://picsum.photos/400?random=32",
        description: "Silent forest cabin perfect for meditation and relaxation.",
        status: "Verified",
        location: "Missoula, Montana",
    },
    {
        id: "33",
        name: "MapleStone Inn",
        date: "2024-02-18",
        propertyType: "Hotel",
        image: "https://picsum.photos/400?random=33",
        description: "Maple-themed boutique inn offering warm hospitality.",
        status: "Verified",
        location: "Toronto, Canada",
    },
    {
        id: "34",
        name: "CoralWave Residence",
        date: "2024-02-01",
        propertyType: "Apartment",
        image: "https://picsum.photos/400?random=34",
        description: "Modern residential complex inspired by ocean patterns.",
        status: "Pending",
        location: "San Francisco, California",
    },
];

